services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://root:123456@db:5432/novelcreateai
    depends_on:
      - db
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: novelcreateai
    volumes:
      - postgres_data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    container_name: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data:
